# Generated by Django 3.1.2 on 2020-11-11 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=70, null=True, verbose_name='From')),
                ('to_address', models.CharField(max_length=70, null=True, verbose_name='To')),
                ('city', models.CharField(blank=True, choices=[('aba', 'Aba'), ('umuahia', 'Umuahia'), ('port harcourt', 'Port Harcourt'), ('owerri', 'Owerri')], max_length=20, null=True)),
                ('no_of_passengers', models.IntegerField(default=1)),
                ('intercity', models.BooleanField(default=False)),
                ('load', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_vehicle_type', models.CharField(blank=True, choices=[('T', 'Tricycle'), ('B', 'Bus'), ('C', 'Car')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unconfirmed', max_length=11)),
                ('price', models.FloatField(default=100.0)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='card', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(max_length=500)),
                ('account_no', models.IntegerField()),
                ('bank', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('unattended', 'Unattended'), ('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unattended', max_length=10)),
            ],
        ),
    ]
