# Generated by Django 3.1.2 on 2020-11-08 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0009_auto_20201108_2141'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=70, null=True, verbose_name='From')),
                ('to_address', models.CharField(max_length=70, null=True, verbose_name='To')),
                ('city', models.CharField(blank=True, choices=[('aba', 'Aba'), ('umuahia', 'Umuahia'), ('port harcourt', 'Port Harcourt'), ('owerri', 'Owerri')], max_length=20, null=True)),
                ('no_of_passengers', models.IntegerField(default=1)),
                ('intercity', models.BooleanField(default=False)),
                ('load', models.BooleanField(default=False)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_vehicle_type', models.CharField(blank=True, choices=[('T', 'Tricycle'), ('B', 'Bus'), ('C', 'Car')], max_length=1, null=True)),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver', to='user.driver')),
                ('passenger', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passenger', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unconfirmed', max_length=11)),
                ('price', models.FloatField(default=100.0)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], default='card', max_length=6)),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ride', to='main.request')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_posted', models.DateTimeField(auto_now_add=True)),
                ('accepted', models.BooleanField(default=False)),
                ('slug', models.SlugField(unique=True)),
                ('driver', models.ManyToManyField(related_name='request_driver', to='user.Driver')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_order', to='main.request')),
            ],
        ),
    ]
