# Generated by Django 3.1.2 on 2020-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201111_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='city',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('aba', 'Aba'), ('umuahia', 'Umuahia'), ('port harcourt', 'Port Harcourt'), ('owerri', 'Owerri')], max_length=20, null=True),
        ),
    ]
