# Generated by Django 3.1.2 on 2020-11-11 19:05

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('firstname', models.CharField(max_length=150)),
                ('lastname', models.CharField(blank=True, max_length=150, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_driver', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(null=True)),
                ('phone', models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number without spaces or hyphens', regex='(?:^[+]{1}[0-9]*$)|(?:^0{1}[0-9]{10}$)')])),
                ('account_balance', models.FloatField(default=0)),
                ('referral', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Who referred you')),
                ('referral_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='unpaid', max_length=6)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics/', verbose_name='Profile Picture')),
                ('location', models.CharField(blank=True, choices=[('aba', 'Aba'), ('umuahia', 'Umuahia'), ('port harcourt', 'Port Harcourt'), ('owerri', 'Owerri')], max_length=20, null=True, verbose_name='Present City')),
                ('status', models.CharField(choices=[('NA', 'Not Avaliable'), ('BU', 'Busy'), ('AV', 'Avaliable')], default='NA', max_length=2, verbose_name='Status')),
                ('journey_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('IN', 'Within The City'), ('OUT', 'Outside Your Current City')], default='IN', max_length=6, null=True, verbose_name='Journey')),
                ('completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(limit_choices_to={'is_driver': True}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('plate_number', models.CharField(blank=True, max_length=15, null=True)),
                ('color', models.CharField(blank=True, max_length=20, null=True)),
                ('capacity', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vehicle_type', models.CharField(blank=True, choices=[('T', 'Tricycle'), ('B', 'Bus'), ('C', 'Car')], max_length=1, null=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='user.driver')),
            ],
        ),
    ]
