# Generated by Django 3.1.2 on 2020-11-02 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Cash'), (2, 'Card')], default=1),
        ),
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unconfirmed'), (2, 'Waiting'), (3, 'Ongoing'), (4, 'Completed')], default=1),
        ),
    ]
