# Generated by Django 3.1.2 on 2020-11-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('aba', 'Aba'), ('umuahia', 'Umuahia'), ('port harcourt', 'Port Harcourt'), ('owerri', 'Owerri')], max_length=20, null=True, verbose_name='Present City'),
        ),
    ]
