# Generated by Django 3.1 on 2020-10-26 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerInfo',
        ),
        migrations.AddField(
            model_name='ride',
            name='reference',
            field=models.CharField(default='not yet paid', max_length=50),
        ),
    ]
