# Generated by Django 3.1 on 2020-10-18 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201018_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='journey_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Within the city'), (2, 'InterCity travel')], default=1, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tricycle'), (2, 'Bus'), (3, 'Car')], null=True),
        ),
    ]
