# Generated by Django 3.1 on 2020-10-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20201014_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('username', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=15)),
                ('about', models.TextField()),
                ('status', models.CharField(choices=[('NA', 'Not Avaliable'), ('BU', 'Busy'), ('AV', 'Avaliable')], default='NA', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
    ]
