# Generated by Django 3.1 on 2020-10-15 20:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_address', models.CharField(max_length=70)),
                ('to_address', models.CharField(max_length=70)),
                ('city', models.CharField(blank=True, choices=[('UMUAHIA', 'Umuahia'), ('ABA', 'Aba')], max_length=15, null=True)),
                ('no_of_passengers', models.IntegerField()),
                ('load', models.BooleanField()),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='driver',
            name='journey_type',
            field=models.CharField(choices=[('IN', 'Within the city'), ('OUT', 'InterCity travel')], default='IN', max_length=3),
        ),
        migrations.AddField(
            model_name='user',
            name='is_driver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, choices=[('UMUAHIA', 'Umuahia'), ('ABA', 'Aba')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('not_avaliable', 'Not Avaliable'), ('busy', 'Busy'), ('avaliable', 'Avaliable')], default='not_avaliable', max_length=13),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('plate_number', models.CharField(max_length=15)),
                ('capacity', models.IntegerField()),
                ('vehicle_type', models.CharField(blank=True, choices=[('T', 'Tricycle'), ('B', 'Bus'), ('C', 'Car')], max_length=1, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('WC', 'Waiting for confirmation'), ('WD', 'Waiting for driver'), ('ON', 'Ongoing'), ('CO', 'Completed')], max_length=2, null=True)),
                ('price', models.FloatField()),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.request')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.driver'),
        ),
        migrations.AddField(
            model_name='request',
            name='passenger',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.passenger'),
        ),
    ]
