# Generated by Django 3.1 on 2020-10-17 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201017_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request', to='user.request'),
        ),
    ]
