# Generated by Django 3.1.2 on 2020-11-17 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
