# Generated by Django 3.1 on 2020-10-18 22:27

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20201018_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='journey_type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Within the city'), (2, 'InterCity travel')], default=1, max_length=3, null=True),
        ),
    ]
