# Generated by Django 3.1.2 on 2020-11-04 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20201104_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='payment_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Unpaid'), (2, 'Paid')], default=1),
        ),
    ]
