# Generated by Django 3.1.2 on 2020-11-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20201104_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='status',
            field=models.CharField(choices=[('unconfirmed', 'Unconfirmed'), ('waiting', 'Waiting'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='unconfirmed', max_length=11),
        ),
    ]
