# Generated by Django 3.1.2 on 2020-11-08 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20201107_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='request',
            name='passenger',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='request',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='Ride',
        ),
    ]
